### ISSUE TITLE
Unable to create Plesk's subscription without hosting

### ISSUE THREAD

**Issue by vbaranovskiy-plesk** [vbaranovskiy-plesk/whmcs-plugin#10]
Steps to reproduce:

1 Add some Plesk as server to provision
2 Settig up a service plan without hosting "No hosting plan" in Plesk
3 Create product in WHMCS and assign it to Plesk's "No hosting plan"
4 Buy some subscription based on this plan

ACTUAL RESULTS:
Subscription is created with hosting

EXPECTED RESULTS:
Subscription is created without hosting

**Comment by GiovanniMet** [comment]
Hi,
news on this issue? I have the same problem.

**Comment by oneumyvakin** [comment]
Plesk internal ID EXTWHMCS-33

**Comment by scardus** [comment]
Does this bug have any chance of being fixed?  It's been over a year since the last update & we now require the ability to setup a subscription with "Physical Hosting" disabled.

**Comment by GiovanniMet** [comment]
I fixed this adding an option in admin panel : https://github.com/plesk/whmcs-plugin/pull/51, you can clone here: https://github.com/GiovanniMet/whmcs-plugin

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
