### ISSUE TITLE
Plesk Usage Statistics Fail with Fatal Error when no accounts are present on the server

### ISSUE THREAD

**Issue by n8whnp** [vbaranovskiy-plesk/whmcs-plugin#11]
When the update usage statistics routine is made in the Plesk module against a Plesk 12.5.30 server which contains no accounts, the following error occurs:

Catchable fatal error: Argument 1 passed to Plesk_Manager_V1630::_getLimits() must be an instance of SimpleXMLElement, null given, called in /var/www/www.xxx.com/modules/servers/plesk/lib/Plesk/Manager/V1640.php on line 0 and defined in /var/www/www.xxx.com/modules/servers/plesk/lib/Plesk/Manager/V1630.php on line 0

Reproduction Steps:
1. Spin up a Plesk 12.5.30 server
2. Login to WHMCS Admin area and enter the server details into Setup > Products/Services > Servers
3. Navigate to Reports > Disk Usage Summary
4. Click "Update Now"
5. Asset: A Catchable fatal error error occurs.

**Comment by jas8522** [comment]
This can be closed.
