### ISSUE TITLE
Plesk Module not creating accounts with dedicated IPs when set as a configurable option

### ISSUE THREAD

**Issue by n8whnp** [vbaranovskiy-plesk/whmcs-plugin#13]
Summary:
Dedicated IPs not provisioning for Plesk
Replication:
Note: These steps assume you have a Plesk Server and package setup in your WHMCS Admin
1. Navigate to Setup > Products/Services > Configurable Options
2. Create configurable options with names Dedicated IPv4 or Dedicated IPv6 depending on the type of IP addresses that you want to offer.
3. Select the Option Type Yes/No for these options.
4. Finally, ensure the products for which you wish to offer these options are selected in the 'Assigned Products' field.
5. Place an order for your Plesk Package and include a dedicated IP
6. Enable Module Debug
7. Accept and create order.
Expected Behaviour:
The module should create a new package on the Plesk Server with a dedicated IP enabled

**Comment by araxy** [comment]
Hello,

will you fix this problem one day?

Because I see that since 2016 you have problems with IP.

Today still it does not work, when I choose in the WHMCS plan options to use a dedicated IP and well it will give a shared IP. With WHMCS 7.6.1 and Plesk 17.8.11.

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
