### ISSUE TITLE
Plesk Module Fails to Change Package for Reseller Type Acccounts

### ISSUE THREAD

**Issue by n8whnp** [vbaranovskiy-plesk/whmcs-plugin#14]
Summary:

When using the Plesk module and trying to upgrade/downgrade a Reseller type account, an error is thrown during the module Change Package event.

Replicate:

Spin up WHMCS 6.2.2
Create a Server using Plesk module (Login deets IP: 208.74.124.12 User: admin Pass: OqqvlVHJJVUQ )
Ensure you have 2 reseller service plans setup in Plesk
Setup 2 products as Reseller type accounts in WHMCS using the plans from Plesk you created above
Create a client and place an order for one of the plesk accounts and accept the order and run the create module command
ASSERT: You should have an active product now and it should be created on the Plesk server
From the product details page, click the upgrade/downgrade option and select your other package to upgrade to and place the order
From the order details page, click on the Reseller Product link which will take you to the Product Details page
Ensure the package has been changed over to the new product package and click the module Change Package
ASSERT: an error is thrown during the upgrade as mentioned above

Example Command Sent:

<?xml version="1.0" encoding="UTF-8"?><packet version="1.6.3.0"><reseller>
    <switch-subscription>
        <filter>
            <id></id>
        </filter>
        <plan-guid>a3d9d758-ed27-0eda-387f-6c4c0bb41ee6</plan-guid>
    </switch-subscription>
</reseller></packet>

Example Response:

<?xml version="1.0"?>
	<packet version="1.6.3.0">
		<system>
			<status>error</status>
			<errcode>1014</errcode>
			<errtext>Parser error: Request is invalid. Error in line 4: Element 'id': '' is not a valid value of the atomic type 'id_type'.</errtext>
		</system>	</packet>

**Comment by agarzon** [comment]
I'm facing the exact same issue, but with WHMCS 7 and Plesk Onyx.

**Comment by jas8522** [comment]
The minor little change referenced in the commit above fixes this issue.

**Comment by oneumyvakin** [comment]
Plesk internal ID EXTWHMCS-34

**Comment by jas8522** [comment]
If you merge that change, this could be closed...

**Comment by jas8522** [comment]
@vbaranovskiy-plesk ?
