### ISSUE TITLE
Creating an Plesk Account w/same username / domain on a second unique plesk server fails w/DB restriction

### ISSUE THREAD

**Issue by n8whnp** [vbaranovskiy-plesk/whmcs-plugin#25]
Details
Summary:
You have a single client and multiple (more than one) plesk servers configured and the client has an account already setup on one Plesk server, when you go to provision the next account on the other Plesk server you will get a SQL error when updating mod_pleskaccounts like so:

Setup WHMCS 
Add 2 plesk servers
Create a hosting service on both servers using the same name and constraints
Create the product in WHMCS using that plesk package name
Create a client and place an order for the product and assign it to one server and create it
ASSERT: You should now have a product assigned to one server successfully
Create another order for that same client for the same product, however this time assign the product to be created on the other server
Run the module create command
ASSERT: You should get an error similar to the above as there is already an entry for this client in the mod_pleskaccounts database table, even though these are on different servers
EXPECT: I would expect that Plesk Module should be able to create multiple accounts across multiple Plesk servers for a single client

Error code: 23000. Error message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7899' for key 'PRIMARY' (SQL: insert into `mod_pleskaccounts` (`userid`, `usertype`, `panelexternalid`) values (7899, reselleraccount, 5fd6ca91-9c48-41d4-9d84-c2a4689a27fb))
Replicate:

**Comment by jas8522** [comment]
Pretty sure this is the same issue as Issue #18

**Comment by jas8522** [comment]
@vbaranovskiy-plesk This can likely be closed in favour of #18

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
