### ISSUE TITLE
Error code: 1013. Error message: Customer with email "xxx"

### ISSUE THREAD

**Issue by jots** [vbaranovskiy-plesk/whmcs-plugin#30]
plesk version 17.5
whmcs version 6.3.2

Login to whmcs as customer (from admin),  click on the plesk service and get:
Error code: 1013. Error message: Customer with email 'XXX' is not found in panel. Please contact your service provider.

error code is:
ERROR_CUSTOMER_WITH_EMAIL_NOT_FOUND_IN_PANEL

any ideas?

**Comment by WHMCS-John** [comment]
Hi @jots ,
Does a Customer with this email address definitely exist in the Plesk panel? I recently encountered a case where there was a Reseller but not a Customer in the panel.

In which case, please ensure the product type in the WHMCS product configuration is appropriately set to "Reseller Account". 
This is done via Setup > Products/Services > Products/Services > Edit. Change the "Product Type" option.

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
