### ISSUE TITLE
Module Creation fails when product type set to Other

### ISSUE THREAD

**Issue by WHMCSChance** [vbaranovskiy-plesk/whmcs-plugin#34]
Setting up a Product in WHMCS as type 'Other' and attempting to run the Module Create command, it will return the following error:

`Error code: 1014. Error message: Parser error: Request is invalid. Error in line 5: Element 'owner-id': '' is not a valid value of the atomic type 'int'.`

*Replicate:*
1. WHMCS 7.4.2
2. Setup Plesk server
3. Create a product and set the type to *Other Product/Service* and module to Plesk then select a service plan from the dropdown.
4. Create a client
5. Place an order for the product under the client
6. From the product details page, click the *Create* module command button
 * Assert: Error is thrown as indicated above
 * Expect: I would expect the error message be clearer as to why this is occurring

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
