### ISSUE TITLE
When account info is updated in WHMCS, it's not propagated to Plesk servers

### ISSUE THREAD

**Issue by Maxpako** [vbaranovskiy-plesk/whmcs-plugin#35]
Hello,
I have a feature request because as I've seen it's not implemented because I cannot find any function UpdateAccount, but plesk_CreateAccount, plesk_SuspendAccount, plesk_UnsuspendAccount and plesk_TerminateAccount.

Request is simple: Whenever an account update its personal data, it doesn't propagate to Plesk servers, keeping there the old data.

Could it be implemented?
Thanks in advance!

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
