### ISSUE TITLE
FAILED: Error code: 1004

### ISSUE THREAD

**Issue by reviewoct** [vbaranovskiy-plesk/whmcs-plugin#36]
hello

i want integrate the plesk module with whmcs 
but after adding the detail ,  i see when i click test connection button : FAILED: Error code: 1004. Error message: Plesk is not configured. Go to the control panel to perform post-installation configuring.

how can i fix this please ?

thanks
amine

**Comment by vbaranovskiy-plesk** [comment]
@reviewoct sorry for delay.
It means that your plesk is not configured somehow. Some of API calls to Plesk just falling. 
You can see it in "Utilities > Logs > Module log" if you are enable debug. 

The main point is that an issue of your Plesk, but not this module. 
You can contant with Plesk support if you need a some help with Plesk configuring:
https://support.plesk.com/hc/en-us
