### ISSUE TITLE
Login to Plesk Control Panel non functional in clientarea product details

### ISSUE THREAD

**Issue by WHMCSChance** [vbaranovskiy-plesk/whmcs-plugin#37]
## Issue

Clicking on the "Login to Plesk Control Panel" button in the Client Area does not successfully log you into the Client Area. Instead it drops you at the login screen.

Video of replication attempt by Chance:
https://screencast.com/t/wyNLNhS2KcgF

## Replicate

1. Install WHMCS Version 7.5.0
2. Activate and configure the "Bank Transfer" gateway
3. Navigate to Setup > Products/Services > Servers and add a new Plesk server 
4. Navigate to Setup > Products/Services > Products/Services and create a Product Group
5. Create a new Product/Service and assign the Plesk module to it
6. Navigate to Clients > Add New Client and create a new Client
7. Click on Add New Order and place a new order for the Plesk service
8. Run the Create command for the new service, and verify that the Plesk account is successfully created
9. Click on the "Login as Client" link, and then navigate to the newly created service in the Client Area
10. Click on the "Login to Plesk Control Panel" button
* ASSERT that you are taken to the login prompt for the Plesk server
* EXPECT to be logged into the Plesk dashboard automatically

It appears that possibly the data is dropped during the 3 redirects that occur after clicking the login button on the product details in the clientarea.  From testing it appears it builds the url as plesk.server:8443/enterprise/rsession_init.php then goes to :8443/login.php and then over to :8443/login_up.php and within all the redirecting the details are either dropped or invalidated.

**Comment by faheemsial** [comment]
Hi dear,

Did you find any solution for this issue? I am experiencing same issue.

**Comment by jpkelly** [comment]
Same here. Any ideas?

**Comment by xiaoyong-wang** [comment]
i have the same issue

**Comment by Er-Abhishek-Kumar** [comment]
Same issue with WHMCS-Bridge, otherwise login working, any idea? how to resolve it.

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
