### ISSUE TITLE
WHMCS 7.5 and this module

### ISSUE THREAD

**Issue by chrisduk112** [vbaranovskiy-plesk/whmcs-plugin#38]
HI

**ISSUE 1**
when i go to configure a new product > module settings

I select the server type PLESK and the server group.

I can see all Hosting Plans on drop down menu
no Reseller Plans show on the reseller Menu.

if i click advanced settings I can manually copy and paste the plan name.

**ISSUE 2**

this could be related to above
when I go to a reseller in WHMCS and click change package I get error:

Module Command Error
Error code: 1014. Error message: Parser error: Request is invalid. Error in line 5: Element 'id': '' is not a valid value of the atomic type 'id_type'.

Plesk Onyx 17.8
Windows Server 2016

**Comment by vbaranovskiy-plesk** [comment]
Two different issues:
issue 1: plesk external id: EXTWHMCS-48
issue 2: Plesk internal ID EXTWHMCS-34

**Comment by chrisduk112** [comment]
when will these be fixed?

**Comment by vbaranovskiy-plesk** [comment]
@chrisduk112 We are planning to merge all fixes to master branch in the next week (now our QA team verify these fixes). Then you can wait until WHMCS will publish a new version (but i can't say when these fixes will be included to a WHMCS inbox ) or just a download files of this repo and simply change all files of this module on your server (of course you should make a backup first)
