### ISSUE TITLE
changing addons fails because of order of operation

### ISSUE THREAD

**Issue by q7joey** [vbaranovskiy-plesk/whmcs-plugin#45]
since the plugin tries to remove addons before adding new ones, it often can't make a change to a subscription because removing the original addon will put the subscription over its allocations.

say base package has 5 email and we've added 1 more email with an addon so the account now has 6 email addresses. trying to change that to have a different addon with 2 additional emails won't work because when it tries to remove the original addon, the subscription is now over committed and the removal fails.

i tweaked the plugin to add the new addons before removing the old ones and that allows the change to proceed.

would you like a patch? it is pretty simple.

**Comment by vbaranovskiy-plesk** [comment]
I'm really sorry for the Late Reply.

Thank you for this issue. It would be really great if you will make a pull request!

**Comment by q7joey** [comment]
i have not used git like this before. am i allowed to create branches in github? i have a local clone of the repo. do i branch first? commit against a branch? can you point me at a doc showing the steps i should go through?

**Comment by q7joey** [comment]
I figured it out, I had no idea the web interface let me do all the forking/editing/requesting bits. You now have a pull request pending.

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
