### ISSUE TITLE
Plesk Account Fails to Create With US Zip Longer Than 5 Digits

### ISSUE THREAD

**Issue by a2mrather** [vbaranovskiy-plesk/whmcs-plugin#46]
When a user creates an account through WHMCS,  user data is accepted with a US post code that is similar to 900101 or 90010-1122. When the US post code is passed over to the Plesk module the account fails to create. Is there a way to disable Plesk's profile validation?

**Comment by vbaranovskiy-plesk** [comment]
I'm really sorry for the Late Reply.

There is no way to skip Plesk's zip code validation. 
The validation rules for US postal codes are following:
 - allow the five-digit (12345)
 - allow the nine-digit (12345-6789)

I've checked this cases and they both works correctly. I've noticed that "900101" code mentioned by you is not valid, but the second code works perfectly. 

Please, check a postal code's value in the API-RPC request (<customer><add>) in Module log in WHMCS. May be there something wrong with it.
