### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by enrikberisha** [vbaranovskiy-plesk/whmcs-plugin#49]
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

Whoops\Exception\ErrorException: The file /var/www/whmcs/modules/servers/pleskExtended/pleskExtended.php was encoded by the ionCube Encoder for PHP 5.6 and cannot run under PHP 7.1 or later.
Please ask the provider of the script to provide a version encoded with the ionCube Encoder for PHP 7.1. in Unknown:0
Stack trace:
#0 /var/www/whmcs/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(16, 'The file /var/w...', 'Unknown', 0)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

Is there a way to get a Version which is encoded for PHP 7.1 or higher?

**Comment by vbaranovskiy-plesk** [comment]
Hello, 
we are not implementing a "pleskExtended" module. Our module is "plesk". So you can ask WHMCS support about contacts of "pleskExtended" developers
