### ISSUE TITLE
Addon installed in WHMCS not updating client subscription in Plesk

### ISSUE THREAD

**Issue by mxdjo** [vbaranovskiy-plesk/whmcs-plugin#55]
When my customers pay for the pack (Hosting + domain), the domain is renewed but the subscription related to the hosting is not updated

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
