### ISSUE TITLE
Change MyISAM to InnoDB for mod_pleskaccounts

### ISSUE THREAD

**Issue by 4ley** [vbaranovskiy-plesk/whmcs-plugin#56]
All tables in WHMCS are InnoDB except "mod_pleskaccounts". As MyISAM is no longer the standard, I would suggest we change it to InnoDB in [Base.php](https://github.com/plesk/whmcs-plugin/blob/557b9191897f66379388113a597de120221c31fe/lib/Plesk/Manager/Base.php#L47)

**Comment by vbaranovskiy-plesk** [comment]
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/
